name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./back

      - name: Run tests and generate coverage report
        run: mvn test jacoco:report
        working-directory: ./back

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: back/target/site/jacoco

      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar
        working-directory: ./back

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./back
          push: false
          tags: ahmid44/bobapp-backend:latest
