name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 16
          
      - name: Install dependencies
        working-directory: front
        run: yarn install

      - name: Run tests
        working-directory: front
        run: npm run test -- --watch=false --code-coverage
        # Vérifier l'existence du rapport de couverture lcov.info
      - name: Check lcov.info existence
        run: ls -la front/coverage

      # Upload du rapport de couverture de test
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: front/coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=ahmidev_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
            -Dsonar.organization=ahmidev
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.exclusions=src/proxy.config.json,src/styles.scss,src/environments/environment.prod.ts,src/environments/environment.ts
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      # Se connecter à Docker Hub avec un jeton d'accès
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./front
          push: true
          tags: ahmid44/bobapp-frontend:latest
